name: 'macOS'
on:
  push:
    branches: [ 'test' ]
  pull_request:
    branches: [ 'test' ]
jobs:
  tests:
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos-13' ]
        php-version: [ '8.3' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'PHP version check'
        uses: 'actions/checkout@v3'
      - run: |
          brew install shivammathur/php/php@${{ matrix.php-version }}
