name: 'macOS'
on:
  push:
    branches: [ 'test' ]
  pull_request:
    branches: [ 'test' ]
jobs:
  tests:
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos-13' ]
        php-version: [ '8.3' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'PHP version check'
        uses: 'actions/checkout@v3'
      - run: |
          echo "Setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK"
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          
          echo "Checking current brew version"
          brew --version
          
          echo "Adding shivammathur/php tap"
          brew tap shivammathur/php
          
          echo "Installing different version"
          if [[ "${{ matrix.php-version }}" == "8.3" ]]; then 
            brew install shivammathur/php/php@8.2
            brew services start shivammathur/php/php@8.2
            brew link --overwrite --force php@8.2
          else
            brew install shivammathur/php/php@8.3
            brew services start shivammathur/php/php@8.3
            brew link --overwrite --force php@8.3
          fi
          
          echo "Installing matrix version"
          brew install shivammathur/php/php@${{ matrix.php-version }}
          
          echo "Setting php to matrix version"
          ./brew-php-switcher.sh ${{ matrix.php-version }}
          version=$(php -v | grep -e '^PHP' | cut -d ' ' -f2 | cut -d '.' -f1,2)
          
          echo "Checking matrix version"
          if [[ "${{ matrix.php-version }}" != "${version}" ]]; then
            echo "Expected ${{ matrix.php-version }} got ${version}"
            exit 1
          else
            echo "PHP CLI version was properly switched to ${{ matrix.php-version }}"
          fi
          
          service="php@${version}"
          status=$(brew services list | grep "${service}" | grep "started")
          
          echo "Checking service status"
          if [[ -z "${status}" ]]; then
            echo "PHP-FPM service with version ${version} is not started"
            exit 1
          else
            echo "PHP-FPM service with version ${version} was started properly"
          fi
