name: 'macOS'
on:
  push:
    branches: [ 'test' ]
  pull_request:
    branches: [ 'test' ]
jobs:
  tests:
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [ 'macos-13' ]
        php-version: [ '8.3' ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'PHP version check'
        uses: 'actions/checkout@v3'
      - run: |
          echo "Setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK"
          export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
          
          echo "Setting HOMEBREW_NO_INSTALL_UPGRADE"
          export HOMEBREW_NO_INSTALL_UPGRADE=1
          
          echo "Checking current brew version"
          brew --version
          
          echo "Adding shivammathur/php tap"
          brew tap shivammathur/php
          
          echo "Installing different version"
          if [[ "${{ matrix.php-version }}" == "8.3" ]]; then 
            brew install php@8.2
            brew services start php@8.2
          else
            brew install php@8.3
            brew services start php@8.3
          fi
          
          php -v
          
          echo "Installing matrix version"
          brew install php@${{ matrix.php-version }}